name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Python Test Linux
      run: docker-compose --file docker-compose-linux-test.yml up --exit-code-from test
      if: runner.os == 'Linux'
    - uses: Homebrew/actions/setup-homebrew@c4aafe8c4620bf08883dd4679c374f11e73329d3
      if: runner.os == 'macOS'
    - run: brew install docker docker-compose docker-machine virtualbox
      if: runner.os == 'macOS'
    - run: |
        docker-machine create --driver virtualbox default
        docker-machine restart
        eval "$(docker-machine env default)"
        docker-machine restart
      if: runner.os == 'macOS'
    - name: Python Test Mac
      run: docker-compose --file docker-compose-mac-test.yml up --exit-code-from test
      if: runner.os == 'macOS'
    - name: Python Test Windows
      run: docker-compose --file docker-compose-windows-test.yml up --exit-code-from test
      if: runner.os == 'Windows'
    - uses: actions/setup-node@v2
    - run: npm ci
    - run: npm test
